version: '3.3'

services:
  application:
    restart: always
    build: ./application
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - "postgresql:postgresql"

  nginx:
    restart: always
    image: nginx:latest
    expose:
      - "8080"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application

  postgresql:
    restart: always
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db

volumes:
  dbdata:
