version: '2'

services:
  application:
    restart: always
    build: ./application
    ports:
      - "8080:8080"
    # volumes:
    #   - 
    # command:
    # depends_on:
    #  - postgresql

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - application

  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgresql:
    restart: always
    build: ./postgresql
    volumes_from:
      - data
    expose:
      - "5432"