version: '2'

services:
  application:
    restart: always
    build: ./application
    ports:
      - "8080:8080"
    # volumes:
    #   -
    # command:
    # depends_on:
    #  - postgresql

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8081:8081"
    depends_on:
      - application

  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql/data
    command: "true"

  postgresql:
    restart: always
    build: ./postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    volumes_from:
     - data
